---
- name: Run Homebrew maintenance tasks
  hosts: localhost
  roles:
    - homebrew
  tasks:
    - name: Update and upgrade Homebrew packages
      include_role:
        name: homebrew
      vars:
        upgrade: true
        cleanup: true
