# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = uwsm app -- hyprsunset
#
#
#
# trebuie reparat acest pisat
# env = AQ_DRM_DEVICES,/dev/dri/by-path/pci-0000:07:00.0-card
#
#
#

