-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Samsung Electric Company S34CG50 HNBW401310",
  mode = "3440x1440@100.00",
  position = "1280x-397",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Thermotrex Corporation TL140ADXP01",
  mode = "2560x1600@120.00",
  position = "0x0",
  scale = 2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
